"use strict";

/**
 * Kho Sỉ Bao Bì — server chính.
 * Chạy: node server.js  (cần Node 20+, dùng fetch() sẵn có của Node)
 * Cấu hình: config.json hoặc biến môi trường TELEGRAM_BOT_TOKEN / TELEGRAM_CHAT_ID / ADMIN_PIN / PORT
 */

const http = require("http");
const fs = require("fs");
const path = require("path");
const crypto = require("crypto");

const ROOT = __dirname;
const PUBLIC = path.join(ROOT, "public");
const CONFIG_PATH = path.join(ROOT, "config.json");
const ORDERS_PATH = path.join(ROOT, "data", "orders.jsonl");
const PRODUCTS_PATH = path.join(ROOT, "data", "products.json");
const DATA_JS_PATH = path.join(PUBLIC, "data.js");
const PORT = Number(process.env.PORT) || 3000;

function loadProducts() {
  try {
    if (fs.existsSync(PRODUCTS_PATH)) {
      return JSON.parse(fs.readFileSync(PRODUCTS_PATH, "utf8"));
    }
  } catch (e) {
    console.error("Error reading products.json:", e);
  }
  return { PRODUCTS: [], USES: [] };
}

function saveProducts(data) {
  fs.writeFileSync(PRODUCTS_PATH, JSON.stringify(data, null, 2) + "\n", "utf8");
  const jsContent = `/* Auto-generated by Admin Manager */\nconst PRODUCTS = ${JSON.stringify(data.PRODUCTS, null, 2)};\n\nconst USES = ${JSON.stringify(data.USES || [], null, 2)};\n\nwindow.PRODUCTS = PRODUCTS;\nwindow.USES = USES;\n`;
  fs.writeFileSync(DATA_JS_PATH, jsContent, "utf8");
}

const SESSION_MS = 12 * 60 * 60 * 1000; // 12 giờ
const MAX_BODY = 200 * 1000; // 200 KB
const MAX_ORDERS = 500; // giữ 500 đơn mới nhất

const sessions = new Map(); // token -> { exp }
const hits = new Map(); // "kind:ip" -> { count, reset }

const MIME = {
  ".html": "text/html; charset=utf-8",
  ".css": "text/css; charset=utf-8",
  ".js": "text/javascript; charset=utf-8",
  ".json": "application/json; charset=utf-8",
  ".svg": "image/svg+xml",
  ".jpg": "image/jpeg",
  ".jpeg": "image/jpeg",
  ".png": "image/png",
  ".webp": "image/webp",
  ".ico": "image/x-icon",
  ".txt": "text/plain; charset=utf-8",
  ".md": "text/markdown; charset=utf-8",
  ".xml": "application/xml; charset=utf-8",
};

const ADMIN_DIST = path.join(ROOT, "admin", "dist");

const SECURITY_HEADERS = {
  "X-Content-Type-Options": "nosniff",
  "X-Frame-Options": "SAMEORIGIN",
  "X-XSS-Protection": "1; mode=block",
  "Referrer-Policy": "strict-origin-when-cross-origin",
  "Permissions-Policy": "camera=(), microphone=(), geolocation=()",
  "Content-Security-Policy": "default-src 'self'; font-src 'self' https://fonts.gstatic.com data:; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://challenges.cloudflare.com; frame-src 'self' https://challenges.cloudflare.com; img-src 'self' data: https: blob:; connect-src 'self' ws: http: https: https://challenges.cloudflare.com;",
};

/* ------------------------------ Cấu hình ------------------------------ */

function loadConfig() {
  let cfg = {};
  try {
    if (fs.existsSync(CONFIG_PATH)) {
      const raw = fs.readFileSync(CONFIG_PATH, "utf8");
      cfg = JSON.parse(raw);
    }
  } catch (e) {
    console.warn("Could not read config.json:", e);
  }
  cfg.brand = cfg.brand || {};
  if (process.env.TELEGRAM_BOT_TOKEN)
    cfg.telegramBotToken = process.env.TELEGRAM_BOT_TOKEN;
  if (process.env.TELEGRAM_CHAT_ID)
    cfg.telegramChatId = process.env.TELEGRAM_CHAT_ID;
  if (process.env.ADMIN_PIN) cfg.adminPin = process.env.ADMIN_PIN;
  if (!cfg.adminPin) cfg.adminPin = "sibaobi2026";
  if (process.env.SHOP_NAME) cfg.brand.name = process.env.SHOP_NAME;
  if (process.env.SHOP_PHONE) cfg.brand.phone = process.env.SHOP_PHONE;
  if (process.env.TURNSTILE_SITE_KEY)
    cfg.turnstileSiteKey = process.env.TURNSTILE_SITE_KEY;
  if (!cfg.turnstileSiteKey) cfg.turnstileSiteKey = "0x4AAAAAAFEbDSKygc5KymKl";
  if (process.env.TURNSTILE_SECRET_KEY)
    cfg.turnstileSecretKey = process.env.TURNSTILE_SECRET_KEY;
  if (!cfg.turnstileSecretKey)
    cfg.turnstileSecretKey = "0x4AAAAAAFEbDdyEY_BZuRYQwzmqd8TWfDc";
  return cfg;
}

function saveConfig(cfg) {
  let existing = {};
  try {
    existing = JSON.parse(fs.readFileSync(CONFIG_PATH, "utf8"));
  } catch {
    existing = {};
  }
  // Token/chât từ biến môi trường không ghi đè lên file, tránh lộ ra config.
  const fileCfg = {
    adminPin: process.env.ADMIN_PIN
      ? existing.adminPin || cfg.adminPin
      : cfg.adminPin,
    telegramBotToken: process.env.TELEGRAM_BOT_TOKEN
      ? existing.telegramBotToken || ""
      : cfg.telegramBotToken || "",
    telegramChatId: process.env.TELEGRAM_CHAT_ID
      ? existing.telegramChatId || ""
      : cfg.telegramChatId || "",
    telegramBotUsername: cfg.telegramBotUsername || "",
    turnstileSiteKey: cfg.turnstileSiteKey || existing.turnstileSiteKey || "0x4AAAAAAFEbDSKygc5KymKl",
    turnstileSecretKey: cfg.turnstileSecretKey || existing.turnstileSecretKey || "0x4AAAAAAFEbDdyEY_BZuRYQwzmqd8TWfDc",
    brand: cfg.brand || existing.brand || {},
  };
  const tmp = CONFIG_PATH + ".tmp";
  fs.writeFileSync(tmp, JSON.stringify(fileCfg, null, 2) + "\n");
  fs.renameSync(tmp, CONFIG_PATH); // ghi atomically, không half-write
}

function publicBrand(cfg) {
  const b = cfg.brand || {};
  return {
    name: b.name || "Kho Sỉ Bao Bì",
    shortName: b.shortName || "Sỉ Bao Bì",
    tagline: b.tagline || "",
    phone: b.phone || "",
    address: b.address || "TP. Hồ Chí Minh",
    hours: b.hours || "",
    area: b.area || "",
  };
}

/* ------------------------------ Tiện ích HTTP ------------------------------ */

function sendJson(res, code, obj) {
  const body = JSON.stringify(obj);
  res.writeHead(
    code,
    Object.assign(
      {
        "Content-Type": "application/json; charset=utf-8",
        "Cache-Control": "no-store",
      },
      SECURITY_HEADERS,
    ),
  );
  res.end(body);
}

function readBody(req) {
  return new Promise((resolve, reject) => {
    const chunks = [];
    let size = 0;
    let failed = false;
    req.on("data", (chunk) => {
      size += chunk.length;
      if (size > MAX_BODY) {
        failed = true;
        const err = new Error("Dữ liệu quá lớn.");
        err.status = 413;
        reject(err);
        req.destroy();
        return;
      }
      chunks.push(chunk);
    });
    req.on("end", () => {
      if (failed) return;
      if (!chunks.length) return resolve({});
      try {
        resolve(JSON.parse(Buffer.concat(chunks).toString("utf8")));
      } catch {
        const err = new Error("Dữ liệu không đọc được.");
        err.status = 400;
        reject(err);
      }
    });
    req.on("error", reject);
  });
}

function clientIp(req) {
  const xf = req.headers["x-forwarded-for"];
  if (typeof xf === "string" && xf.trim()) return xf.split(",")[0].trim();
  return req.socket.remoteAddress || "0";
}

/* ------------------------------ Chống spam ------------------------------ */

function tooMany(ip, key, limit, windowMs) {
  const id = key + ":" + ip;
  const now = Date.now();
  let rec = hits.get(id);
  if (!rec || rec.reset < now) {
    rec = { count: 0, reset: now + windowMs };
    hits.set(id, rec);
  }
  rec.count += 1;
  return rec.count > limit;
}

function clearHits(ip, key) {
  hits.delete(key + ":" + ip);
}

async function verifyTurnstile(token, ip) {
  const cfg = loadConfig();
  const secret = process.env.TURNSTILE_SECRET_KEY || cfg.turnstileSecretKey;
  if (!secret) return true;
  if (!token) return false;
  try {
    const params = new URLSearchParams();
    params.append("secret", secret);
    params.append("response", token);
    if (ip) params.append("remoteip", ip);
    const res = await fetch("https://challenges.cloudflare.com/turnstile/v0/siteverify", {
      method: "POST",
      headers: { "Content-Type": "application/x-www-form-urlencoded" },
      body: params.toString(),
      signal: AbortSignal.timeout(6000),
    });
    const data = await res.json();
    return Boolean(data && data.success);
  } catch (err) {
    console.error("Turnstile error:", err);
    return false;
  }
}

// Dọn bộ đếm và phiên hết hạn định kỳ.
setInterval(
  () => {
    const now = Date.now();
    for (const [k, v] of hits) if (v.reset < now) hits.delete(k);
    for (const [k, v] of sessions) if (v.exp < now) sessions.delete(k);
  },
  10 * 60 * 1000,
).unref();

/* ------------------------------ Phiên đăng nhập ------------------------------ */

function safeEqual(a, b) {
  const ba = Buffer.from(String(a));
  const bb = Buffer.from(String(b));
  if (ba.length !== bb.length) return false;
  return crypto.timingSafeEqual(ba, bb);
}

function parseCookies(req) {
  const out = {};
  for (const part of String(req.headers.cookie || "").split(";")) {
    const i = part.indexOf("=");
    if (i < 1) continue;
    try {
      out[part.slice(0, i).trim()] = decodeURIComponent(
        part.slice(i + 1).trim(),
      );
    } catch {
      out[part.slice(0, i).trim()] = part.slice(i + 1).trim();
    }
  }
  return out;
}

function getSession(req) {
  const token = parseCookies(req).admin_session;
  if (!token) return null;
  const session = sessions.get(token);
  if (!session || session.exp < Date.now()) {
    if (token) sessions.delete(token);
    return null;
  }
  return { token, ...session };
}

function setSessionCookie(req, res, token, maxAge) {
  const parts = [
    "admin_session=" + token,
    "HttpOnly",
    "SameSite=Lax",
    "Path=/",
    "Max-Age=" + maxAge,
  ];
  if (isHttps(req)) parts.push("Secure");
  res.setHeader("Set-Cookie", parts.join("; "));
}

function isHttps(req) {
  const proto = String(req.headers["x-forwarded-proto"] || "")
    .split(",")[0]
    .trim()
    .toLowerCase();
  return proto === "https";
}

/* ------------------------------ Làm sạch dữ liệu ------------------------------ */

function esc(value) {
  return String(value == null ? "" : value)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;");
}

function clean(value, max) {
  return String(value == null ? "" : value)
    .replace(/[\u0000-\u001F\u007F]/g, "")
    .trim()
    .slice(0, max);
}

function normalizePhone(raw) {
  let digits = String(raw || "").replace(/[^\d+]/g, "");
  if (digits.startsWith("+84")) digits = "0" + digits.slice(3);
  else if (digits.startsWith("84") && digits.length >= 11)
    digits = "0" + digits.slice(2);
  return digits;
}

function validPhone(digits) {
  return /^0(3|5|7|8|9)\d{8}$/.test(digits);
}

function prettyPhone(digits) {
  if (digits.length === 10) {
    return (
      digits.slice(0, 4) + " " + digits.slice(4, 7) + " " + digits.slice(7)
    );
  }
  return digits;
}

function formatQty(n) {
  const num = Number(n);
  if (!Number.isFinite(num)) return String(n);
  return num.toLocaleString("vi-VN", { maximumFractionDigits: 2 });
}

function nowLabel() {
  return new Date().toLocaleString("vi-VN", {
    timeZone: "Asia/Ho_Chi_Minh",
    hour12: false,
    day: "2-digit",
    month: "2-digit",
    year: "numeric",
    hour: "2-digit",
    minute: "2-digit",
  });
}

/* ------------------------------ Telegram ------------------------------ */

function normalizeToken(raw) {
  let token = clean(raw, 200).replace(/\s+/g, "");
  token = token.replace(/^https?:\/\/api\.telegram\.org\/bot/i, "");
  token = token.replace(/\/.*$/, "");
  if (/^bot\d+/i.test(token)) token = token.slice(3);
  return token;
}

function validToken(token) {
  return /^\d{5,}:[A-Za-z0-9_-]{10,}$/.test(token);
}

function maskToken(token) {
  if (!token) return "";
  if (token.length < 14) return "••••";
  return token.slice(0, 7) + "…" + token.slice(-4);
}

async function tg(token, method, payload) {
  if (!validToken(token)) {
    const err = new Error("Token bot chưa đúng định dạng.");
    err.status = 400;
    throw err;
  }
  const url = "https://api.telegram.org/bot" + token + "/" + method;
  let res;
  try {
    res = await fetch(url, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(payload || {}),
      signal: AbortSignal.timeout(15000),
    });
  } catch {
    const err = new Error(
      "Không gọi được Telegram. Kiểm tra mạng của máy chủ.",
    );
    err.status = 502;
    throw err;
  }
  const data = await res.json().catch(() => ({}));
  if (!res.ok || data.ok === false) {
    const err = new Error(
      translateTg(data.description, data.error_code, res.status),
    );
    err.status = Number.isInteger(data.error_code)
      ? data.error_code
      : res.status;
    err.description = data.description || "";
    throw err;
  }
  return data;
}

function translateTg(description, code, status) {
  const d = String(description || "");
  const low = d.toLowerCase();
  if (code === 401 || low.includes("unauthorized"))
    return "Token bot không dùng được. Hãy copy lại token từ BotFather.";
  if (code === 409 || low.includes("webhook"))
    return "Bot đang gắn webhook nên chưa đọc được hội thoại. Dán chat ID bằng tay, hoặc bấm tạm tắt webhook.";
  if (low.includes("chat not found"))
    return "Không thấy chat ID này. Hãy nhắn tin cho bot trước, rồi tìm lại chat ID.";
  if (low.includes("blocked"))
    return "Bot đã bị chặn. Mở Telegram, bỏ chặn bot rồi gửi lại.";
  if (low.includes("not enough rights"))
    return "Bot chưa có quyền gửi tin trong nhóm. Hãy cho bot quyền gửi tin nhắn.";
  if (!d) return "Telegram không nhận yêu cầu (mã " + status + ").";
  return "Telegram báo: " + d;
}

function buildMessage(order, brandName) {
  const isSample = Boolean(order.isSample);
  const lines = [
    isSample
      ? "<b>📦 ĐĂNG KÝ NHẬN MẪU THỬ MIỄN PHÍ</b>"
      : "<b>YÊU CẦU TƯ VẤN MỚI</b>",
    "",
  ];
  lines.push("<b>Khách:</b> " + esc(order.name));
  lines.push("<b>Zalo:</b> " + esc(order.phonePretty));
  if (order.address) lines.push("<b>Địa chỉ nhận mẫu:</b> " + esc(order.address));
  if (order.logo) lines.push("<b>In logo:</b> Có");
  if (order.note) lines.push("<b>Ghi chú:</b> " + esc(order.note));
  lines.push(
    "",
    isSample ? "<b>Mẫu sản phẩm đã chọn:</b>" : "<b>Sản phẩm đã chọn:</b>",
  );
  order.items.forEach((item, index) => {
    lines.push(index + 1 + ". <b>" + esc(item.name) + "</b>");
    if (item.size) lines.push("   • Size: " + esc(item.size));
    if (item.color) lines.push("   • Màu: " + esc(item.color));
    if (item.spec)
      lines.push(
        "   • " + esc(item.specLabel || "Loại") + ": " + esc(item.spec),
      );
    if (item.extra && item.extra !== "Theo kho tư vấn") {
      lines.push(
        "   • " + esc(item.extraLabel || "Thêm") + ": " + esc(item.extra),
      );
    }
    lines.push(
      "   • Số lượng: <b>" +
        esc(formatQty(item.qty)) +
        " " +
        esc(item.unit) +
        "</b>",
    );
  });
  lines.push(
    "",
    esc(brandName || "Kho") + " · gửi từ web lúc " + esc(order.timeLabel),
  );
  let text = lines.join("\n");
  if (text.length > 3900) text = text.slice(0, 3890) + "\n…";
  return text;
}

function extractChats(updates) {
  const map = new Map();
  for (const update of updates || []) {
    const chat =
      (update.message && update.message.chat) ||
      (update.edited_message && update.edited_message.chat) ||
      (update.channel_post && update.channel_post.chat) ||
      (update.my_chat_member && update.my_chat_member.chat) ||
      (update.chat_member && update.chat_member.chat);
    if (!chat || chat.id == null) continue;
    const title =
      chat.title ||
      [chat.first_name, chat.last_name].filter(Boolean).join(" ") ||
      (chat.username ? "@" + chat.username : String(chat.id));
    map.set(String(chat.id), {
      id: String(chat.id),
      type: chat.type || "",
      title,
      username: chat.username || "",
    });
  }
  return Array.from(map.values());
}

/* ------------------------------ Đơn hàng ------------------------------ */

function parseItems(raw) {
  if (!Array.isArray(raw) || !raw.length || raw.length > 30) return null;
  const units = new Set(["kg", "cái", "xấp", "bộ", "mẫu"]);
  const items = [];
  for (const row of raw) {
    if (!row || typeof row !== "object") return null;
    const qty = Number(row.qty);
    const unit = clean(row.unit, 12);
    if (!Number.isFinite(qty) || qty <= 0 || qty > 1000000) return null;
    if (!units.has(unit)) return null;
    const name = clean(row.name, 120);
    if (name.length < 2) return null;
    items.push({
      id: clean(row.id, 40),
      name,
      size: clean(row.size, 80),
      color: clean(row.color, 40),
      spec: clean(row.spec, 40),
      specLabel: clean(row.specLabel, 40),
      extra: clean(row.extra, 40),
      extraLabel: clean(row.extraLabel, 40),
      qty,
      unit,
    });
  }
  return items;
}

function appendOrder(order) {
  fs.mkdirSync(path.dirname(ORDERS_PATH), { recursive: true });
  fs.appendFileSync(ORDERS_PATH, JSON.stringify(order) + "\n");
  try {
    const lines = fs
      .readFileSync(ORDERS_PATH, "utf8")
      .split("\n")
      .filter(Boolean);
    if (lines.length > MAX_ORDERS) {
      fs.writeFileSync(ORDERS_PATH, lines.slice(-MAX_ORDERS).join("\n") + "\n");
    }
  } catch {
    /* không giữ được lịch sử thì bỏ qua, đơn mới vẫn được ghi */
  }
}

function readOrders(limit) {
  if (!fs.existsSync(ORDERS_PATH)) return [];
  const lines = fs
    .readFileSync(ORDERS_PATH, "utf8")
    .split("\n")
    .filter(Boolean);
  return lines
    .slice(-limit)
    .reverse()
    .map((line) => {
      try {
        return JSON.parse(line);
      } catch {
        return null;
      }
    })
    .filter(Boolean);
}

/* ------------------------------ Trang tĩnh ------------------------------ */

function serveStatic(req, res, pathname) {
  if (pathname === "/admin") {
    res.writeHead(302, { Location: "/admin/" });
    res.end();
    return;
  }
  if (pathname === "/admin/" || pathname.startsWith("/admin/")) {
    if (fs.existsSync(ADMIN_DIST)) {
      let sub = pathname.slice("/admin/".length);
      try {
        sub = decodeURIComponent(sub);
      } catch {}
      let resolved = path.resolve(ADMIN_DIST, sub);
      if (!resolved.startsWith(ADMIN_DIST)) {
        res.writeHead(403, SECURITY_HEADERS);
        res.end("Forbidden");
        return;
      }
      try {
        if (!fs.existsSync(resolved) || fs.statSync(resolved).isDirectory()) {
          resolved = path.join(ADMIN_DIST, "index.html");
        }
      } catch {
        resolved = path.join(ADMIN_DIST, "index.html");
      }
      const ext = path.extname(resolved).toLowerCase();
      const isImage = [".jpg", ".jpeg", ".png", ".webp", ".svg", ".ico"].includes(ext);
      res.writeHead(
        200,
        Object.assign(
          {
            "Content-Type": MIME[ext] || "application/octet-stream",
            "Cache-Control": isImage ? "public, max-age=604800" : "no-cache",
          },
          SECURITY_HEADERS,
        ),
      );
      if (req.method === "HEAD") {
        res.end();
        return;
      }
      fs.createReadStream(resolved).pipe(res);
      return;
    }
  }

  let rel = pathname;
  if (rel === "/" || rel === "/index.html") rel = "/index.html";
  else if (rel === "/quan-tri" || rel === "/quan-tri/") rel = "/quan-tri.html";
  try {
    rel = decodeURIComponent(rel);
  } catch {
    res.writeHead(400, SECURITY_HEADERS);
    res.end("Bad request");
    return;
  }
  if (rel.includes("\0")) {
    res.writeHead(400, SECURITY_HEADERS);
    res.end("Bad request");
    return;
  }
  const resolved = path.resolve(PUBLIC, "." + rel);
  if (resolved !== PUBLIC && !resolved.startsWith(PUBLIC + path.sep)) {
    res.writeHead(403, SECURITY_HEADERS);
    res.end("Forbidden");
    return;
  }
  fs.stat(resolved, (err, stat) => {
    if (err || !stat.isFile()) return serve404(res);
    const ext = path.extname(resolved).toLowerCase();
    const isImage = [".jpg", ".jpeg", ".png", ".webp", ".svg", ".ico"].includes(
      ext,
    );
    res.writeHead(
      200,
      Object.assign(
        {
          "Content-Type": MIME[ext] || "application/octet-stream",
          "Cache-Control": isImage ? "public, max-age=604800" : "no-cache",
        },
        SECURITY_HEADERS,
      ),
    );
    if (req.method === "HEAD") {
      res.end();
      return;
    }
    fs.createReadStream(resolved).pipe(res);
  });
}

function serve404(res) {
  res.writeHead(
    404,
    Object.assign(
      { "Content-Type": "text/html; charset=utf-8" },
      SECURITY_HEADERS,
    ),
  );
  res.end(
    "<!doctype html><html lang='vi'><meta charset='utf-8'><meta name='viewport' content='width=device-width,initial-scale=1'>" +
      "<title>Không thấy trang</title><body style='font-family:system-ui,sans-serif;display:grid;place-items:center;min-height:80vh;margin:0'>" +
      "<div style='text-align:center;padding:24px'><p style='font-size:2rem;margin:0'>📦</p>" +
      "<p style='font-weight:700;font-size:1.1rem;margin:8px 0'>Không thấy trang này.</p>" +
      "<a href='/' style='color:#175c43;font-weight:700'>Về kho hàng →</a></div></body></html>",
  );
}

/* ------------------------------ API ------------------------------ */

async function handleSiteApi(res) {
  const cfg = loadConfig();
  sendJson(res, 200, {
    ok: true,
    brand: publicBrand(cfg),
    turnstileSiteKey: cfg.turnstileSiteKey || "0x4AAAAAAFEbDSKygc5KymKl",
  });
}

async function handleLead(req, res) {
  const ip = clientIp(req);
  if (tooMany(ip, "lead", 20, 15 * 60 * 1000)) {
    return sendJson(res, 429, {
      ok: false,
      error: "Bạn gửi hơi nhiều lần. Đợi một lát rồi thử lại.",
    });
  }
  const body = await readBody(req);
  if (clean(body.hp_field, 80))
    return sendJson(res, 200, { ok: true, delivered: true }); // bẫy bot

  // Xác minh Cloudflare Turnstile
  const turnstileToken = body.turnstileToken || body["cf-turnstile-response"];
  const isHuman = await verifyTurnstile(turnstileToken, ip);
  if (!isHuman) {
    return sendJson(res, 400, {
      ok: false,
      error: "Xác minh bảo mật chống bot chưa hoàn tất hoặc thất bại. Vui lòng tích chọn xác minh.",
    });
  }

  const name = clean(body.name, 80);
  const phone = normalizePhone(body.phone);
  const note = clean(body.note, 500);
  const logo = Boolean(body.logo);
  const items = parseItems(body.items);
  if (name.length < 2)
    return sendJson(res, 400, { ok: false, error: "Bạn cho mình xin tên." });
  if (!validPhone(phone))
    return sendJson(res, 400, {
      ok: false,
      error: "Số Zalo chưa đúng. Nhập 10 số, ví dụ 0901234567.",
    });
  if (!items)
    return sendJson(res, 400, {
      ok: false,
      error: "Chưa có sản phẩm hợp lệ. Bạn chọn hàng rồi gửi lại.",
    });

  const isSample = Boolean(body.isSample);
  const address = clean(body.address, 200);
  const cfg = loadConfig();
  const order = {
    at: new Date().toISOString(),
    timeLabel: nowLabel(),
    name,
    phone,
    phonePretty: prettyPhone(phone),
    address,
    isSample,
    note,
    logo,
    items,
    delivered: false,
    telegramError: "",
  };

  let delivered = false;
  let telegramError = "";
  if (cfg.telegramBotToken && cfg.telegramChatId) {
    try {
      const text = buildMessage(order, cfg.brand && cfg.brand.name);
      await tg(cfg.telegramBotToken, "sendMessage", {
        chat_id: cfg.telegramChatId,
        text,
        parse_mode: "HTML",
        disable_web_page_preview: true,
      });
      delivered = true;
    } catch (e) {
      telegramError = e.message || "Không gửi được Telegram.";
    }
  } else {
    telegramError = "Chưa cấu hình bot.";
  }
  order.delivered = delivered;
  order.telegramError = telegramError;
  appendOrder(order);

  if (!delivered) {
    return sendJson(res, 502, {
      ok: false,
      saved: true,
      error: cfg.telegramBotToken
        ? "Đã ghi đơn tại kho nhưng chưa gửi sang Telegram. Bạn thử lại giúp, hoặc nhắn trực tiếp cho kho."
        : "Kho chưa kết nối Telegram. Đơn đã được ghi lại. Bạn thử lại sau ít phút.",
    });
  }
  return sendJson(res, 200, { ok: true, delivered: true });
}

function requireAdmin(req, res) {
  const cfg = loadConfig();
  const pinHeader = req.headers["x-admin-pin"];
  if (pinHeader && safeEqual(String(pinHeader), String(cfg.adminPin || ""))) {
    return cfg;
  }
  if (!getSession(req)) {
    sendJson(res, 401, {
      ok: false,
      error: "Bạn cần đăng nhập trang quản trị.",
    });
    return null;
  }
  return cfg;
}

async function handleAdmin(req, res, url) {
  const pathname = url.pathname;

  if (pathname === "/api/admin/login" && req.method === "POST") {
    const ip = clientIp(req);
    if (tooMany(ip, "pin", 10, 15 * 60 * 1000)) {
      return sendJson(res, 429, {
        ok: false,
        error: "Thử sai quá nhiều lần. Đợi 15 phút.",
      });
    }
    const body = await readBody(req);

    // Xác minh Cloudflare Turnstile
    const turnstileToken = body.turnstileToken || body["cf-turnstile-response"];
    const isHuman = await verifyTurnstile(turnstileToken, ip);
    if (!isHuman) {
      return sendJson(res, 400, {
        ok: false,
        error: "Xác minh bảo mật chống bot chưa hoàn tất hoặc thất bại. Vui lòng thử lại.",
      });
    }

    const cfg = loadConfig();
    if (!safeEqual(String(body.pin || ""), String(cfg.adminPin || ""))) {
      return sendJson(res, 401, { ok: false, error: "Mã quản trị chưa đúng." });
    }
    clearHits(ip, "pin");
    const token = crypto.randomBytes(24).toString("hex");
    sessions.set(token, { exp: Date.now() + SESSION_MS });
    setSessionCookie(req, res, token, SESSION_MS / 1000);
    return sendJson(res, 200, { ok: true });
  }

  if (pathname === "/api/admin/logout" && req.method === "POST") {
    const session = getSession(req);
    if (session) sessions.delete(session.token);
    setSessionCookie(req, res, "", 0);
    return sendJson(res, 200, { ok: true });
  }

  const cfg = requireAdmin(req, res);
  if (!cfg) return;

  if (pathname === "/api/admin/status" && req.method === "GET") {
    return sendJson(res, 200, {
      ok: true,
      configured: Boolean(cfg.telegramBotToken && cfg.telegramChatId),
      hasToken: Boolean(cfg.telegramBotToken),
      botUsername: cfg.telegramBotUsername || "",
      chatId: cfg.telegramChatId || "",
      maskedToken: maskToken(cfg.telegramBotToken || ""),
      brand: publicBrand(cfg),
    });
  }

  if (pathname === "/api/admin/check" && req.method === "POST") {
    const body = await readBody(req);
    const token = normalizeToken(body.token || cfg.telegramBotToken);
    const data = await tg(token, "getMe", {});
    const me = data.result || {};
    return sendJson(res, 200, {
      ok: true,
      username: me.username || "",
      name: me.first_name || "",
      token,
    });
  }

  if (pathname === "/api/admin/chats" && req.method === "POST") {
    const body = await readBody(req);
    const token = normalizeToken(body.token || cfg.telegramBotToken);
    const data = await tg(token, "getUpdates", { limit: 30, timeout: 0 });
    return sendJson(res, 200, { ok: true, chats: extractChats(data.result) });
  }

  if (pathname === "/api/admin/delete-webhook" && req.method === "POST") {
    const body = await readBody(req);
    const token = normalizeToken(body.token || cfg.telegramBotToken);
    await tg(token, "deleteWebhook", { drop_pending_updates: false });
    return sendJson(res, 200, { ok: true });
  }

  if (pathname === "/api/admin/save" && req.method === "POST") {
    const body = await readBody(req);
    const next = loadConfig();
    if (body.token) {
      const token = normalizeToken(body.token);
      if (!validToken(token))
        return sendJson(res, 400, {
          ok: false,
          error: "Token chưa đúng. Copy nguyên dòng token từ BotFather.",
        });
      const me = await tg(token, "getMe", {});
      next.telegramBotToken = token;
      next.telegramBotUsername = (me.result && me.result.username) || "";
    }
    if (body.chatId != null && String(body.chatId).trim() !== "") {
      const chatId = clean(body.chatId, 40).replace(/\s+/g, "");
      if (!/^-?\d+$/.test(chatId) && !/^@[A-Za-z0-9_]{4,}$/.test(chatId)) {
        return sendJson(res, 400, {
          ok: false,
          error: "Chat ID chỉ gồm số, ví dụ 123456789 hoặc -1001234567890.",
        });
      }
      next.telegramChatId = chatId;
    }
    if (body.brand && typeof body.brand === "object") {
      const b = body.brand;
      const phone = clean(b.phone, 20);
      if (phone && !validPhone(normalizePhone(phone))) {
        return sendJson(res, 400, {
          ok: false,
          error: "Số điện thoại hiển thị trên web chưa đúng.",
        });
      }
      next.brand = {
        name: clean(b.name, 60) || next.brand.name,
        shortName: clean(b.shortName, 40) || next.brand.shortName,
        tagline: clean(b.tagline, 80),
        phone: phone ? prettyPhone(normalizePhone(phone)) : "",
        address: clean(b.address, 120) || next.brand.address,
        hours: clean(b.hours, 80),
        area: clean(b.area, 120),
      };
    }
    if (body.newPin) {
      const pin = clean(body.newPin, 40);
      if (pin.length < 6)
        return sendJson(res, 400, {
          ok: false,
          error: "Mã quản trị mới cần ít nhất 6 ký tự.",
        });
      next.adminPin = pin;
    }
    saveConfig(next);
    return sendJson(res, 200, {
      ok: true,
      configured: Boolean(next.telegramBotToken && next.telegramChatId),
      botUsername: next.telegramBotUsername || "",
      chatId: next.telegramChatId || "",
      maskedToken: maskToken(next.telegramBotToken || ""),
      brand: publicBrand(next),
    });
  }

  if (pathname === "/api/admin/test" && req.method === "POST") {
    if (!cfg.telegramBotToken || !cfg.telegramChatId) {
      return sendJson(res, 400, {
        ok: false,
        error: "Chưa có token hoặc chat ID. Lưu cấu hình trước.",
      });
    }
    await tg(cfg.telegramBotToken, "sendMessage", {
      chat_id: cfg.telegramChatId,
      text: "Tin thử từ web Kho Sỉ Bao Bì.\nKết nối thành công. Đơn tư vấn của khách sẽ gửi về đây.",
    });
    return sendJson(res, 200, { ok: true });
  }

  if (pathname === "/api/admin/products" && req.method === "GET") {
    const data = loadProducts();
    return sendJson(res, 200, { ok: true, products: data.PRODUCTS, uses: data.USES });
  }

  if (pathname === "/api/admin/products" && req.method === "POST") {
    const body = await readBody(req);
    if (!body || !Array.isArray(body.products)) {
      return sendJson(res, 400, { ok: false, error: "Dữ liệu sản phẩm không hợp lệ." });
    }
    const current = loadProducts();
    const updated = {
      PRODUCTS: body.products,
      USES: body.uses || current.USES || [],
    };
    saveProducts(updated);
    return sendJson(res, 200, { ok: true, count: updated.PRODUCTS.length });
  }

  if (pathname === "/api/admin/orders" && req.method === "GET") {
    const rawOrders = readOrders(150);
    const orders = rawOrders.map((order, idx) => {
      let totalAmount = 0;
      const items = (order.items || []).map((it, itemIdx) => {
        const qty = Number(it.qty) || 1;
        const price = Number(it.price) || 35000;
        const total = price * qty;
        totalAmount += total;
        return {
          id: `item-${idx}-${itemIdx}`,
          productId: it.id || 'prod',
          name: it.name || 'Sản phẩm bao bì',
          size: it.size || '',
          color: it.color || '',
          qty,
          unit: it.unit || 'kg',
          price,
          total,
        };
      });

      return {
        id: `ord-${idx}-${new Date(order.at).getTime() || Date.now()}`,
        code: order.code || `DH-${(order.at || '').slice(0, 10).replace(/-/g, '')}-${String(idx + 1).padStart(3, '0')}`,
        customerName: order.name || 'Khách liên hệ',
        customerPhone: order.phonePretty || order.phone || '',
        items,
        totalAmount: order.totalAmount || totalAmount || 500000,
        status: order.status || (order.delivered ? 'confirmed' : 'pending'),
        createdAt: order.at || new Date().toISOString(),
        note: order.note || '',
        hasLogo: Boolean(order.logo),
        deliveredTelegram: Boolean(order.delivered),
      };
    });
    return sendJson(res, 200, { ok: true, orders });
  }

  if (pathname === "/api/admin/orders/status" && req.method === "POST") {
    const body = await readBody(req);
    const { code, status } = body;
    if (!code || !status) {
      return sendJson(res, 400, { ok: false, error: "Thiếu thông tin cập nhật." });
    }
    if (fs.existsSync(ORDERS_PATH)) {
      const lines = fs.readFileSync(ORDERS_PATH, "utf8").split("\n").filter(Boolean);
      const newLines = lines.map(line => {
        try {
          const ord = JSON.parse(line);
          const ordCode = ord.code || `DH-${(ord.at || '').slice(0, 10).replace(/-/g, '')}`;
          if (ord.code === code || ordCode.includes(code)) {
            ord.status = status;
          }
          return JSON.stringify(ord);
        } catch {
          return line;
        }
      });
      fs.writeFileSync(ORDERS_PATH, newLines.join("\n") + "\n", "utf8");
    }
    return sendJson(res, 200, { ok: true });
  }

  if (pathname === "/api/admin/orders/delete" && req.method === "POST") {
    const body = await readBody(req);
    const { code, id, at, phone, clearAll } = body;
    if (clearAll) {
      if (fs.existsSync(ORDERS_PATH)) {
        fs.writeFileSync(ORDERS_PATH, "", "utf8");
      }
      return sendJson(res, 200, { ok: true, cleared: true });
    }
    if (!code && !id && !at && !phone) {
      return sendJson(res, 400, { ok: false, error: "Thiếu thông tin để xóa." });
    }
    if (fs.existsSync(ORDERS_PATH)) {
      const lines = fs.readFileSync(ORDERS_PATH, "utf8").split("\n").filter(Boolean);
      const cleanPhone = phone ? String(phone).replace(/\D/g, "") : "";
      const remainingLines = lines.filter((line) => {
        try {
          const ord = JSON.parse(line);
          if (at && ord.at === at) return false;
          if (id && ord.at && id.includes(String(new Date(ord.at).getTime()))) return false;
          const ordCode = ord.code || `DH-${(ord.at || "").slice(0, 10).replace(/-/g, "")}`;
          if (code && (ord.code === code || ordCode === code || ordCode.includes(code))) return false;
          if (cleanPhone) {
            const ordPhone = String(ord.phone || "").replace(/\D/g, "");
            const ordPhonePretty = String(ord.phonePretty || "").replace(/\D/g, "");
            if (ordPhone === cleanPhone || ordPhonePretty === cleanPhone) return false;
          }
          return true;
        } catch {
          return true;
        }
      });
      fs.writeFileSync(ORDERS_PATH, remainingLines.join("\n") + (remainingLines.length > 0 ? "\n" : ""), "utf8");
    }
    return sendJson(res, 200, { ok: true });
  }

  return sendJson(res, 404, { ok: false, error: "Không thấy API này." });
}

/* ------------------------------ Router ------------------------------ */

async function handle(req, res) {
  const url = new URL(req.url, "http://127.0.0.1");
  const pathname = url.pathname;

  if (pathname === "/healthz") return sendJson(res, 200, { ok: true });
  if (pathname === "/api/site" && req.method === "GET")
    return handleSiteApi(res);
  if (pathname === "/api/tu-van" && req.method === "POST")
    return handleLead(req, res);
  if (pathname.startsWith("/api/admin/")) return handleAdmin(req, res, url);
  if (pathname.startsWith("/api/"))
    return sendJson(res, 404, { ok: false, error: "Không thấy API này." });

  if (req.method !== "GET" && req.method !== "HEAD") {
    res.writeHead(405, Object.assign({ Allow: "GET, HEAD" }, SECURITY_HEADERS));
    res.end("Method not allowed");
    return;
  }
  serveStatic(req, res, pathname);
}

const server = http.createServer((req, res) => {
  handle(req, res).catch((err) => {
    console.error(err);
    if (res.headersSent) return;
    const status = Number(err.status) || 500;
    sendJson(res, status >= 400 && status < 600 ? status : 500, {
      ok: false,
      error: err.status ? err.message || "Lỗi máy chủ." : "Lỗi máy chủ.",
    });
  });
});

server.listen(PORT, "0.0.0.0", () => {
  console.log("Kho Sỉ Bao Bì đang chạy tại http://localhost:" + PORT);
});
